import unittest
import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

#Prepared by Erik Brousseau, John Gombas, Cody Amend

class admin_scripts(unittest.TestCase):
    # this sets up the location of the chrome driver
    def setUp(self):
        self.driver = webdriver.Chrome("C://python/gameboyz/myvenv/scripts/chromedriver.exe")
    #Prepared by Erik Brousseau
    def test_Admin(self):
        # admin login
        driver = self.driver
        driver.maximize_window()
        driver.get("http://ebrousseau.pythonanywhere.com/admin")
        time.sleep(2)
        elem = driver.find_element_by_id("id_username")
        time.sleep(2)
        elem.send_keys("admin")
        elem = driver.find_element_by_id("id_password")
        elem.send_keys("eb708199")
        time.sleep(2)
        elem.send_keys(Keys.RETURN)
        assert "Logged In"
        time.sleep(3)
        driver.get("http://ebrousseau.pythonanywhere.com/admin")

        # add group (Prepared by John Gombas)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/auth/group")
        time.sleep(2)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/auth/group/add/")
        elem = driver.find_element_by_id("id_name")
        elem.send_keys("Test_Group_Sel")
        time.sleep(2)
        elem = driver.find_element_by_name("_save")
        elem.click()
        time.sleep(2)

        # update group (Prepared by John Gombas)

        driver.get("http://ebrousseau.pythonanywhere.com/admin/auth/group/")
        time.sleep(4)
        elem = driver.find_element_by_link_text("Test_Group_Sel")
        elem.click()
        elem = driver.find_element_by_id("id_name")
        elem.clear()
        time.sleep(2)
        elem.send_keys("Test_Group_Sel_update")
        time.sleep(4)
        elem = driver.find_element_by_name("_save")
        elem.click()
        time.sleep(2)

        # delete group (Prepared by John Gombas)

        driver.get("http://ebrousseau.pythonanywhere.com/admin/auth/group/")
        time.sleep(3)
        elem = driver.find_element_by_link_text("Test_Group_Sel_update")
        elem.click()
        elem = driver.find_element_by_link_text("Delete")
        elem.click()
        time.sleep(2)
        elem = driver.find_element_by_xpath("//input[2]")
        elem.click()
        time.sleep(2)

        # add user (Prepared by John Gombas)
        driver.get("http://ebrousseau.pythonanywhere.com/admin")
        time.sleep(2)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/auth/user/")
        time.sleep(2)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/auth/user/add/")
        elem = driver.find_element_by_id("id_username")
        elem.clear()
        elem.send_keys("Test_User_Sel")
        elem = driver.find_element_by_id("id_password1")
        elem.clear()
        time.sleep(2)
        elem.send_keys("instructor1a")
        elem = driver.find_element_by_id("id_password2")
        elem.clear()
        elem.send_keys("instructor1a")
        time.sleep(2)
        elem = driver.find_element_by_name("_save")
        elem.click()
        time.sleep(2)

        # update user (Prepared by John Gombas)

        driver.get("http://ebrousseau.pythonanywhere.com/admin/auth/user/")
        time.sleep(2)
        elem = driver.find_element_by_link_text("Test_User_Sel")
        elem.click()
        elem = driver.find_element_by_id("id_username")
        elem.clear()
        elem.send_keys("Test_User_Sel_Update")
        elem = driver.find_element_by_id("id_first_name")
        elem.clear()
        time.sleep(2)
        elem.send_keys("Test")
        elem = driver.find_element_by_id("id_last_name")
        elem.clear()
        elem.send_keys("User")
        time.sleep(2)
        elem = driver.find_element_by_id("id_email")
        elem.clear()
        elem.send_keys("jgombas@unomaha.edu")
        time.sleep(4)
        elem = driver.find_element_by_name("_save")
        elem.click()
        time.sleep(2)

        # delete user (Prepared by John Gombas)

        driver.get("http://ebrousseau.pythonanywhere.com/admin/auth/user/")
        time.sleep(3)
        elem = driver.find_element_by_link_text("Test_User_Sel_Update")
        elem.click()
        elem = driver.find_element_by_link_text("Delete")
        elem.click()
        time.sleep(2)
        elem = driver.find_element_by_xpath("//input[2]")
        elem.click()
        time.sleep(3)

        # create category (Prepared by John Gombas)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/shop/category")
        time.sleep(2)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/shop/category/add/")
        elem = driver.find_element_by_id("id_name")
        elem.send_keys("Games_Sel")
        time.sleep(3)
        elem = driver.find_element_by_name("_save")
        elem.click()
        time.sleep(3)

        # update category (Prepared by John Gombas)

        driver.get("http://ebrousseau.pythonanywhere.com/admin/shop/category/")
        time.sleep(3)
        elem = driver.find_element_by_link_text("Games_Sel")
        elem.click()
        elem = driver.find_element_by_id("id_name")
        elem.clear()
        elem.send_keys("Games_Sel_update")
        time.sleep(4)
        elem = driver.find_element_by_name("_save")
        elem.click()
        time.sleep(3)

        # delete category (Prepared by John Gombas)

        driver.get("http://ebrousseau.pythonanywhere.com/admin/shop/category/")
        time.sleep(3)
        elem = driver.find_element_by_link_text("Games_Sel_update")
        elem.click()
        elem = driver.find_element_by_link_text("Delete")
        elem.click()
        time.sleep(2)
        elem = driver.find_element_by_xpath("//input[2]")
        elem.click()
        time.sleep(3)

        # create game (Prepared by John Gombas)

        driver.get("http://ebrousseau.pythonanywhere.com/admin/shop/product/")
        time.sleep(2)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/shop/product/add/")
        elem = driver.find_element_by_xpath("//select[@id='id_category']/option[2]")
        elem.click()
        elem = driver.find_element_by_id("id_name")
        elem.send_keys("Game_Sel")
        elem = driver.find_element_by_id("id_description")
        elem.send_keys("Test Game")
        elem = driver.find_element_by_id("id_price")
        elem.send_keys("60.00")
        time.sleep(4)
        elem = driver.find_element_by_name("_save")
        elem.click()
        time.sleep(3)

    
        # update game (Prepared by John Gombas)

        driver.get("http://ebrousseau.pythonanywhere.com/admin/shop/product/")
        time.sleep(3)
        elem = driver.find_element_by_link_text("Game_Sel")
        elem.click()
        elem = driver.find_element_by_id("id_name")
        elem.clear()
        elem.send_keys("Game_Sel_update")
        time.sleep(2)
        elem = driver.find_element_by_id("id_description")
        elem.clear()
        elem.send_keys("Test Game Update")
        elem = driver.find_element_by_id("id_price")
        elem.clear()
        elem.send_keys("30.00")
        time.sleep(2)
        elem = driver.find_element_by_id("id_slug")
        elem.clear()
        elem.send_keys("game_sel_update")
        time.sleep(4)
        elem = driver.find_element_by_name("_save")
        elem.click()
        time.sleep(3)

        # delete game (Prepared by John Gombas)

        driver.get("http://ebrousseau.pythonanywhere.com/admin/shop/product/")
        time.sleep(3)
        elem = driver.find_element_by_link_text("Game_Sel_update")
        elem.click()
        elem = driver.find_element_by_link_text("Delete")
        elem.click()
        time.sleep(2)
        elem = driver.find_element_by_xpath("//input[2]")
        elem.click()
        time.sleep(3)



        # get orders (Prepared by John Gombas)

        driver.get("http://ebrousseau.pythonanywhere.com/admin")
        time.sleep(2)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/orders/order/")
        time.sleep(3)
        elem = driver.find_element_by_link_text("38")
        elem.click()
        time.sleep(5)

        # get social auth (Prepared by Erik Brousseau and John Gombas)

        driver.get("http://ebrousseau.pythonanywhere.com/admin")
        time.sleep(2)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/social_django/usersocialauth/")
        time.sleep(3)
        elem = driver.find_element_by_link_text("jgombas")
        elem.click()
        time.sleep(3)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/social_django/usersocialauth/")
        time.sleep(3)
        elem = driver.find_element_by_link_text("ErikBrousseau")
        elem.click()
        time.sleep(3)

        #get streaming information (Prepared by Erik Brousseau)

        driver.get("http://ebrousseau.pythonanywhere.com/admin/")
        time.sleep(2)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/streaming/stream/")
        time.sleep(3)
        elem = driver.find_element_by_link_text("Fortnite")
        elem.click()
        time.sleep(3)

        driver.get("http://ebrousseau.pythonanywhere.com/admin/login/?next=/admin/")

        # Create Coupon (Prepared by Cody Amend)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/")
        time.sleep(2)
        elem = driver.find_element_by_xpath("/html/body/div/div[2]/div[1]/div[2]/table/tbody/tr/td[1]/a").click()
        time.sleep(2)
        elem = driver.find_element_by_id("id_code")
        elem.send_keys("1111")
        elem = driver.find_element_by_xpath(
            "/html/body/div[1]/div[3]/div/form/div/fieldset/div[2]/div/p/span[1]/a[1]").click()
        elem = driver.find_element_by_xpath(
            "/html/body/div[1]/div[3]/div/form/div/fieldset/div[2]/div/p/span[2]/a[1]").click()
        time.sleep(1)
        elem = driver.find_element_by_id("id_valid_to_0")
        elem.send_keys("2018-12-31")
        elem = driver.find_element_by_id("id_valid_to_1")
        elem.send_keys("12:00:00")
        elem = driver.find_element_by_id("id_discount")
        elem.send_keys("15")
        time.sleep(1)
        elem = driver.find_element_by_xpath("/html/body/div[1]/div[3]/div/form/div/fieldset/div[5]/div/label").click()
        elem = driver.find_element_by_xpath("/html/body/div[1]/div[3]/div/form/div/div/input[1]").click()
        time.sleep(2)
        # Edit Coupon (Prepared by Cody Amend)
        elem = driver.find_element_by_xpath("/html/body/div/div[3]/div/div/form/div[2]/table/tbody/tr[1]/th/a").click()
        time.sleep(2)
        elem = driver.find_element_by_id("id_discount")
        elem.clear()
        elem.send_keys("25")
        elem = driver.find_element_by_xpath("/html/body/div[1]/div[3]/div/form/div/div/input[1]").click()
        time.sleep(1)
        # Delete Coupon (Prepared by Cody Amend)
        elem = driver.find_element_by_xpath("/html/body/div/div[3]/div/div/form/div[2]/table/tbody/tr[1]/th/a").click()
        time.sleep(1)
        elem = driver.find_element_by_xpath("/html/body/div[1]/div[3]/div/form/div/div/p/a").click()
        elem = driver.find_element_by_xpath("/html/body/div/div[3]/form/div/input[2]").click()
        time.sleep(1)


        # add comment (Prepared by Erik Brousseau)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/")
        time.sleep(2)
        elem = driver.find_element_by_xpath("/html/body/div/div[2]/div[1]/div[3]/table/tbody/tr/th/a").click()
        time.sleep(2)
        elem = driver.find_element_by_xpath("/html/body/div/div[3]/div/ul/li/a").click()
        elem = driver.find_element_by_xpath(
            "/html/body/div[1]/div[3]/div/form/div/fieldset[1]/div[1]/div/div/select/option[5]").click()
        time.sleep(2)
        elem = driver.find_element_by_id("id_object_pk")
        elem.send_keys("15")
        time.sleep(2)
        elem = driver.find_element_by_xpath(
            "/html/body/div[1]/div[3]/div/form/div/fieldset[1]/div[3]/div/div/select/option[2]").click()
        time.sleep(2)
        elem = driver.find_element_by_id("id_user")
        elem.send_keys("1")
        time.sleep(2)
        elem = driver.find_element_by_id("id_user_name")
        elem.send_keys("admin")
        time.sleep(2)
        elem = driver.find_element_by_id("id_user_email")
        elem.send_keys("pythonrocks225@gmail.com")
        elem = driver.find_element_by_xpath("//*[@id='id_comment']")
        elem.send_keys("another test comment")
        time.sleep(2)
        elem = driver.find_element_by_xpath("/html/body/div[1]/div[3]/div/form/div/fieldset[3]/div[1]/div/p/span[1]/a[1]").click()
        elem = driver.find_element_by_xpath("/html/body/div[1]/div[3]/div/form/div/fieldset[3]/div[1]/div/p/span[2]/a[1]").click()
        time.sleep(2)
        elem = driver.find_element_by_xpath("/html/body/div[1]/div[3]/div/form/div/div/input[1]").click()
        time.sleep(4)

        #edit comment (Prepared by Erik Brousseau)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/django_comments/comment/")
        elem = driver.find_element_by_xpath("/html/body/div/div[3]/div/div/form/div[2]/table/tbody/tr[1]/th/a").click()
        time.sleep(2)
        elem = driver.find_element_by_xpath("//*[@id='id_comment']")
        elem.send_keys(" another test comment 2")
        time.sleep(2)
        elem = driver.find_element_by_xpath("/html/body/div[1]/div[3]/div/form/div/div/input[1]").click()
        time.sleep(2)

        #Delete comment (Prepared by Erik Brousseau)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/django_comments/comment/")
        elem = driver.find_element_by_xpath("/html/body/div/div[3]/div/div/form/div[2]/table/tbody/tr[1]/th/a").click()
        time.sleep(2)
        elem = driver.find_element_by_xpath("/html/body/div[1]/div[3]/div/form/div/div/p/a").click()
        elem = driver.find_element_by_xpath("/html/body/div/div[3]/form/div/input[2]").click()
        time.sleep(2)

        # Create Profile (Prepared by Erik Brousseau)
        driver.get("http://ebrousseau.pythonanywhere.com/admin/")
        elem = driver.find_element_by_xpath("/html/body/div/div[2]/div[1]/div[6]/table/tbody/tr[3]/th/a").click()
        elem = driver.find_element_by_xpath("/html/body/div/div[3]/div/ul/li/a").click()
        time.sleep(2)
        elem = driver.find_element_by_xpath(
            "/html/body/div[1]/div[3]/div/form/div/fieldset/div[1]/div/div/select/option[14]").click()
        elem = driver.find_element_by_id("id_phone_number")
        time.sleep(2)
        elem.send_keys("402-657-1789")
        elem = driver.find_element_by_xpath(
            "/html/body/div[1]/div[3]/div/form/div/fieldset/div[3]/div/span[1]/a[1]").click()
        elem = driver.find_element_by_xpath("/html/body/div[1]/div[3]/div/form/div/div/input[1]").click()
        time.sleep(2)

        # Update Profile (Prepared by Erik Brousseau)
        elem = driver.find_element_by_xpath("/html/body/div/div[3]/div/div/form/div[2]/table/tbody/tr[1]/th/a").click()
        elem = driver.find_element_by_id("id_phone_number")
        time.sleep(2)
        elem.clear()
        elem.send_keys("402-829-4567")
        time.sleep(2)
        elem = driver.find_element_by_xpath("/html/body/div[1]/div[3]/div/form/div/div/input[1]").click()
        time.sleep(2)

        # Delete Profile (Prepared by Erik Brousseau)
        elem = driver.find_element_by_xpath("/html/body/div/div[3]/div/div/form/div[2]/table/tbody/tr[1]/th/a").click()
        time.sleep(2)
        elem = driver.find_element_by_xpath("/html/body/div[1]/div[3]/div/form/div/div/p/a").click()
        elem = driver.find_element_by_xpath("/html/body/div/div[3]/form/div/input[2]").click()
        time.sleep(2)








    def tearDown(self):
        self.driver.close()
